# Generated by Django 3.1.5 on 2021-01-21 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Instangram', '0002_auto_20210121_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(upload_to='', verbose_name='image'),
        ),
    ]
